//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESCPOSTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESCPOSTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print File.
        /// </summary>
        public static string BUTTON_PRINT_FILE {
            get {
                return ResourceManager.GetString("BUTTON_PRINT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print String.
        /// </summary>
        public static string BUTTON_PRINT_STRING {
            get {
                return ResourceManager.GetString("BUTTON_PRINT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [drop].
        /// </summary>
        public static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bin].
        /// </summary>
        public static string DROP_BIN {
            get {
                return ResourceManager.GetString("DROP_BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Bytes from File as ESC/POS Commands.
        /// </summary>
        public static string PRINT_DROP_TIP {
            get {
                return ResourceManager.GetString("PRINT_DROP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag binary file (.bin, .prn, etc) to print.
        /// </summary>
        public static string PRINT_DROP_TIP_BIN {
            get {
                return ResourceManager.GetString("PRINT_DROP_TIP_BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Any File From File System.
        /// </summary>
        public static string PRINT_FILE_TIP {
            get {
                return ResourceManager.GetString("PRINT_FILE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print PRN File.
        /// </summary>
        public static string PRINT_FILE_TIP_BIN {
            get {
                return ResourceManager.GetString("PRINT_FILE_TIP_BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type String in Above Text Box.
        /// </summary>
        public static string PRINT_STRING_TIP {
            get {
                return ResourceManager.GetString("PRINT_STRING_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Printer.
        /// </summary>
        public static string TARGET_PRINTER {
            get {
                return ResourceManager.GetString("TARGET_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of The Adventures of Sherlock Holmes
        ///by Sir Arthur Conan Doyle
        ///(#15 in our series by Sir Arthur Conan Doyle)
        ///
        ///Copyright laws are changing all over the world. Be sure to check the
        ///copyright laws for your country before downloading or redistributing
        ///this or any other Project Gutenberg eBook.
        ///
        ///This header should be the first thing seen when viewing this Project
        ///Gutenberg file.  Please do not remove it.  Do not change or edit the
        ///header without written permission.
        ///
        ///Please [rest of string was truncated]&quot;;.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTI Printer Test Utility.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
